[package]
name = "asuka"
version = "1.2.0"
authors = ["Alex Díaz"]
edition = "2021"

[dependencies]
colored = "2.1.0"
log = "0.4.22"
log4rs = "1.3.0"
dotenvy = "0.15.7"
chrono = "0.4.38"
chrono-tz = "0.10.0"
serde = { version = "1.0.214", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.132"
json = "0.12.4"
serenity = "0.12.2"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
